
title: Juan Rizo
description: Personal site of Juan Rizo
author: Juan Rizo
location: Lima, Peru 🇵🇪
email: ngzhio@gmail.com
paginate: 20
subscribe: false
avatar: /avatar.jpg

author_profile: true

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: dark

author:
  name     : "Juan Rizo"
  avatar   : "/avatar.jpg"
  bio      : "I'm a software engineer. Build things"
  location : "Lima, Peru 🇵🇪"
  twitter  : Milhouse_Van_Ho

include:
  - _pages
  
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache  
