
title: Juan Rizo
description: Personal site of Juan Rizo

# remote_theme: mmistakes/minimal-mistakes@4.22.0
# minimal_mistakes_skin: "dark"

#remote_theme           : "mmistakes/minimal-mistakes"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# markdown: kramdown

atom_feed:
  hide: true

author:
  name     : "Juan Rizo"
  avatar   : "/avatar.jpg"
  bio      : "I'm a software engineer. Build things"
  location : "Lima, Peru 🇵🇪"
  twitter  : Milhouse_Van_Ho
  linkedin : "sebmart"
  github : "sebmart"

include:
  - _pages
  
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache  
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
